sudo: required
language: python
python:
  - "2.7"

before_install: "sudo apt-get update"

install:
# Install linuxbrew and install dependencies
- "sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev"
- "ruby -e $(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
- "brew tap homebrew/science qsirianni/bioinformatics"
- "brew install bcftools samtools bowtie2 karect"

# Install PIP dependencies
- "pip install psutil"

# Run the test script
script: "test.py"

