sudo: required
language: python
python:
  - "2.7"

before_install:
- "sudo apt-get update"

install:
# Install samtools
- "sudo apt-get install samtools"

# Install bowtie2
- "sudo apt-get install bowtie2"

# Install karect
- "wget https://github.com/aminallam/karect/archive/v1.0.tar.gz"
- "tar -xzvf v1.0.tar.gz"
- "cd karect-1.0"
- "make"
- "export PATH=$PWD:$PATH"
- "cd ../"

# Install bcftools
- "sudo apt-get zlib1g-dev"
- "wget https://github.com/samtools/bcftools/archive/1.2.tar.gz"
- "tar -xzvf 1.2.tar.gz"
- "cd bcftools-1.2"
- "make && make install"


# Install PIP dependencies
- "pip install psutil"

# Run the test script
script: "test.py"

