os: osx
language: python
python:
  # Supported python runtime environments
  - "2.7"
  - "3.5"

# Setup homebrew for dependency installation
before_install:
  - "brew tap homebrew/science qsirianni/bioinformatics"
  - "brew update"

# Install grapple's dependencies using homebrew and pip
install:
  - "brew install samtools karect bowtie2 bcftools"
  - "pip install -r requirements.txt"

# Run the test script
script: "./test.py"

