sudo: required
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"

# Update apt-get
before_install: "sudo apt-get update"

install:
  # Install dependencies for Homebrew
  - "sudo apt-get -y install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev
     libncurses-dev zlib1g-dev"

  # Install homebrew and update PATH
  - "git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew"
  - "export PATH=\"$HOME/.linuxbrew/bin:$PATH\""
  - "export MANPATH=\"$HOME/.linuxbrew/share/man:$MANPATH\""
  - "export INFOPATH=\"$HOME/.linuxbrew/share/info:$INFOPATH\""

  # Install dependencies from Homebrew
  - "brew tap homebrew/science"
  - "brew tap qsirianni/bioinformatics"
  - "brew install samtools karect bowtie2 bcftools"

  # Install dependencies from pip
  - "pip install -r requirements.txt"

# Run the test script
script: "./test.py"

