language: python
python:
  - "2.7"

# Install external dependencies
before_script:
  - "wget https://github.com/aminallam/karect/archive/v1.0.tar.gz -O karect.tar.gz"
  - "tar -xzf karect.tar.gz"
  - "cd karect && make"
  - "export PATH=$PWD:$PATH"

before_install:
  - "sudo apt-get install bowtie2"
  - "sudo apt-get install samtools"
  - "sudo apt-get install bcftools"

# Install PIP dependencies
install: "pip install -r requirements.txt"

# Run the test script
script: "test.py"

